#ifndef __S2_INTEGRA_DBS_301_PARSING_H__
#define __S2_INTEGRA_DBS_301_PARSING_H__




/*
* Constructor and Destructor
*/

/*
* DIGITAL_INPUT
*/
#define __S2_INTEGRA_DBS_301_PARSING_DEBUG_DIG_INPUT 0


/*
* ANALOG_INPUT
*/


#define __S2_INTEGRA_DBS_301_PARSING_RX$_BUFFER_INPUT 0
#define __S2_INTEGRA_DBS_301_PARSING_RX$_BUFFER_MAX_LEN 200
CREATE_STRING_STRUCT( S2_INTEGRA_DBS_301_PARSING, __RX$, __S2_INTEGRA_DBS_301_PARSING_RX$_BUFFER_MAX_LEN );


/*
* DIGITAL_OUTPUT
*/
#define __S2_INTEGRA_DBS_301_PARSING_POWER_FB_DIG_OUTPUT 0


/*
* ANALOG_OUTPUT
*/
#define __S2_INTEGRA_DBS_301_PARSING_TRANSPORT_ANALOG_OUTPUT 0
#define __S2_INTEGRA_DBS_301_PARSING_MEDIA_ANALOG_OUTPUT 1
#define __S2_INTEGRA_DBS_301_PARSING_DIMMER_ANALOG_OUTPUT 2
#define __S2_INTEGRA_DBS_301_PARSING_ASPECT_ANALOG_OUTPUT 3
#define __S2_INTEGRA_DBS_301_PARSING_HDMI_RESOLUTION_ANALOG_OUTPUT 4
#define __S2_INTEGRA_DBS_301_PARSING_HDMI_SETUP_ANALOG_OUTPUT 5
#define __S2_INTEGRA_DBS_301_PARSING_LANGUAGE_ANALOG_OUTPUT 6
#define __S2_INTEGRA_DBS_301_PARSING_TITLE_CURRENT_ANALOG_OUTPUT 7
#define __S2_INTEGRA_DBS_301_PARSING_TITLE_TOTAL_ANALOG_OUTPUT 8
#define __S2_INTEGRA_DBS_301_PARSING_CHAPTER_CURRENT_ANALOG_OUTPUT 9
#define __S2_INTEGRA_DBS_301_PARSING_CHAPTER_TOTAL_ANALOG_OUTPUT 10
#define __S2_INTEGRA_DBS_301_PARSING_TIME_HOURS_ANALOG_OUTPUT 11
#define __S2_INTEGRA_DBS_301_PARSING_TIME_MINUTES_ANALOG_OUTPUT 12
#define __S2_INTEGRA_DBS_301_PARSING_TIME_SECONDS_ANALOG_OUTPUT 13
#define __S2_INTEGRA_DBS_301_PARSING_TIME_TOTALSEC_ANALOG_OUTPUT 14



/*
* Direct Socket Variables
*/




/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* STRING_PARAMETER
*/


/*
* INTEGER
*/


/*
* LONG_INTEGER
*/


/*
* SIGNED_INTEGER
*/


/*
* SIGNED_LONG_INTEGER
*/


/*
* STRING
*/
#define __S2_INTEGRA_DBS_301_PARSING_KEY$_ARRAY_NUM_ELEMS 12
#define __S2_INTEGRA_DBS_301_PARSING_KEY$_ARRAY_NUM_CHARS 4
CREATE_STRING_ARRAY( S2_INTEGRA_DBS_301_PARSING, __KEY$, __S2_INTEGRA_DBS_301_PARSING_KEY$_ARRAY_NUM_ELEMS, __S2_INTEGRA_DBS_301_PARSING_KEY$_ARRAY_NUM_CHARS );

/*
* STRUCTURE
*/

START_GLOBAL_VAR_STRUCT( S2_INTEGRA_DBS_301_PARSING )
{
   void* InstancePtr;
   struct GenericOutputString_s sGenericOutStr;
   unsigned short LastModifiedArrayIndex;

   DECLARE_STRING_ARRAY( S2_INTEGRA_DBS_301_PARSING, __KEY$ );
   DECLARE_STRING_STRUCT( S2_INTEGRA_DBS_301_PARSING, __RX$ );
};

START_NVRAM_VAR_STRUCT( S2_INTEGRA_DBS_301_PARSING )
{
};



#endif //__S2_INTEGRA_DBS_301_PARSING_H__

